name: tekartik_js_qr
description: Cozmo JsQR dart wrapper
deploy_to: none
version: 0.1.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta:
  js:
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart2

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  process_run:
  test:

dependency_overrides:
  pedantic: '>=1.9.0'